swagger: "2.0"
info:
  version: "0.1.0"
  title: eSaude Admin API
host: localhost:2580
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /app:
    x-swagger-router-controller: app
    get:
      description: Retrieve containers
      operationId: getAllApps
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllAppsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /about:
    x-swagger-router-controller: about
    get:
      description: General information about the eSaude Admin API
      operationId: about
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AboutResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /docker/container:
    x-swagger-router-controller: container
    get:
      description: Retrieve containers
      operationId: getAllContainers
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllContainersResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /backup:
    x-swagger-router-controller: backup
    get:
      description: Retrieve list of backups
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllBackupsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create backup
      operationId: create
      parameters:
        - name: type
          description: Backup file to retrieve
          required: false
          type: string
          enum:
            - database
            - module
            - war
            - bundle
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"    
  /backup/{filename}:
    x-swagger-router-controller: backup
    get:
      description: Retrieve backup file
      produces:
        - application/zip
      operationId: get
      parameters:
        - name: filename
          description: Backup file to retrieve
          required: true
          type: string
          in: path
      responses:
        "200":
          description: Success
          schema:
            type: file
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  AboutResponse:
    type: object
    properties:
      description:
        type: string
      version:
        type: string
      homepage:
        type: string
      license:
        type: string
      bugs:
        type: object
        properties:
          url: 
            type: string
          email:
            type: string
  AllBackupsResponse:
    type: object
    properties:
      database:
        type: array
        items:
          type: object
          properties:
            filename:
              type: string
            size:
              type: number
            created:
              type: string
  AppResponse:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      version:
        type: string
      containers:
        type: array
        items:
          $ref: "#/definitions/ContainerResponse"    
  AllAppsResponse:
    type: array
    items:
      $ref: "#/definitions/AppResponse"
  ContainerResponse:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      image:
        type: object
        properties:
          registry:
            type: string
          name:
            type: string
          version:
            type: string
      ports:
        type: array
        items:
          type: object
          properties:
            ip:
              type: string
            private:
              type: number
            public:
              type: number
            protocol:
              type: string
      networks:
        type: array
        items:
          type: string
      mounts:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
            name:
              type: string
            source:
              type: string
            destination:
              type: string
      created:
        type: object
        properties:
          timestamp:
            type: number
          display:
            type: string
      state:
        type: string
      status:
        type: string
  AllContainersResponse:
    type: array
    items:
      $ref: "#/definitions/ContainerResponse"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
