swagger: "2.0"
info:
  version: "0.1.0"
  title: eSaude Admin API
host: localhost:2580
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /about:
    x-swagger-router-controller: about
    get:
      description: General information about the eSaude Admin API
      operationId: about
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AboutResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  AboutResponse:
    type: object
    properties:
      description:
        type: string
      version:
        type: string
      homepage:
        type: string
      license:
        type: string
      bugs:
        type: object
        properties:
          url: 
            type: string
          email:
            type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
