swagger: "2.0"
info:
  version: "0.1.0"
  title: eSaude Admin API
host: localhost:2580
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /about:
    x-swagger-router-controller: about
    get:
      description: General information about the eSaude Admin API
      operationId: about
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AboutResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /backup:
    x-swagger-router-controller: backup
    get:
      description: Retrieve list of backups
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllBackupsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create backup
      operationId: create
      parameters:
        - name: type
          description: Backup file to retrieve
          required: false
          type: string
          enum:
            - database
            - module
            - war
            - bundle
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"    
  /backup/{filename}:
    x-swagger-router-controller: backup
    get:
      description: Retrieve backup file
      produces:
        - application/zip
      operationId: get
      parameters:
        - name: filename
          description: Backup file to retrieve
          required: true
          type: string
          in: path
      responses:
        "200":
          description: Success
          schema:
            type: file
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  AboutResponse:
    type: object
    properties:
      description:
        type: string
      version:
        type: string
      homepage:
        type: string
      license:
        type: string
      bugs:
        type: object
        properties:
          url: 
            type: string
          email:
            type: string
  AllBackupsResponse:
    type: object
    properties:
      database:
        type: array
        items:
          type: object
          properties:
            filename:
              type: string
            size:
              type: number
            created:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
